#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

fn-deployment-keys-app-has-keys() {
  declare APP="$1"
  local app_specific_key_folder="$DOKKU_ROOT/.deployment-keys/$APP/.ssh"

  if [[ -f "$app_specific_key_folder/id_rsa.pub" ]]; then
    echo "This app already has a pair of keys. Delete them first to create new ones"
    exit 1
  fi
}

fn-deployment-keys-create-private-key-folder() {
  declare APP="$1"
  local app_specific_key_folder="$DOKKU_ROOT/.deployment-keys/$APP/.ssh"

  if [[ ! -d "$app_specific_key_folder" ]]; then
    mkdir -p "$app_specific_key_folder"
    chown -R dokku:dokku "$DOKKU_ROOT/.deployment-keys/$APP"
  fi
}
