[plugin]
name = "dokku-deployment-keys"
description = "Provides a Dokku Plugin for injecting SSH deployment keys to the container"
version = "0.1.0"
website_url = "https://github.com/expa/dokku-deployment-keys"
[plugin.config]
