#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

delete-cmd() {
  #E delete the current pair of deployment keys
  #E dokku $PLUGIN_COMMAND_PREFIX:delete my-app
  #A app, app to run command against
  declare desc="delete the current pair of deployment keys"
  local cmd="$PLUGIN_COMMAND_PREFIX:delete" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  APP=${APP:="$DOKKU_APP_NAME"}

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  local app_specific_key_folder="$DOKKU_ROOT/.deployment-keys/$APP/.ssh"
  rm -Rf "$app_specific_key_folder"/id_rsa*
  dokku_log_info1_quiet "Removed deployment keys for $APP"
}

delete-cmd "$@"
