#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

show-cmd() {
  #E shows the current public key to add to your VCS
  #E dokku $PLUGIN_COMMAND_PREFIX:show my-app
  #A app, app to run command against
  declare desc="shows the current public key to add to your VCS"
  local cmd="$PLUGIN_COMMAND_PREFIX:show" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  APP=${APP:="$DOKKU_APP_NAME"}

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  local app_specific_key_folder="$DOKKU_ROOT/.deployment-keys/$APP/.ssh"
  if [[ -f "$app_specific_key_folder/id_rsa.pub" ]]; then
    echo "Private keys created, here is the public key for $APP:"
    cat "$app_specific_key_folder/id_rsa.pub"
  else
    echo "No private key for $APP. This is the shared public key:"
    local shared_key_folder="$DOKKU_ROOT/.deployment-keys/shared/.ssh"
    cat "$shared_key_folder/id_rsa.pub"
  fi
}

show-cmd "$@"
