#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

status-cmd() {
  #E shows the current status of the deployment keys for an app
  #E dokku $PLUGIN_COMMAND_PREFIX:status my-app
  #A app, app to run command against
  declare desc="shows the current status of the deployment keys for an app"
  local cmd="$PLUGIN_COMMAND_PREFIX:status" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  APP=${APP:="$DOKKU_APP_NAME"}

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  local app_specific_key_folder="$DOKKU_ROOT/.deployment-keys/$APP/.ssh"
  if [[ -f "$app_specific_key_folder/id_rsa.pub" ]]; then
    echo "This app uses a private set of deployment keys."
  else
    echo "This app uses the shared set of deployment keys."
  fi
}

status-cmd "$@"
